name: flutter_cloud_run
repository: https://github.com/kweinmeister/flutter-cloud-run

packages:
  - backend
  - frontend
  - shared

scripts:
  analyze:
    run: dart run melos exec -- "dart analyze ."
    description: Run `dart analyze` in all packages.

  test:
    run: dart run melos run test:dart && dart run melos run test:flutter
    description: Run all tests in the workspace.

  test:dart:
    run: dart run melos exec -- "dart test"
    packageFilters:
      dirExists: test
      flutter: false
    description: Run Dart tests in the workspace.

  test:flutter:
    run: dart run melos exec -- "flutter test"
    packageFilters:
      dirExists: test
      flutter: true
    description: Run Flutter tests in the workspace.

  test:coverage:
    run: dart run melos run test:coverage:dart && dart run melos run test:coverage:flutter
    description: Run all tests with coverage.

  test:coverage:dart:
    run: |
      dart run melos exec -- \
        "dart test --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib"
    packageFilters:
      dirExists: test
      flutter: false
    description: Run Dart tests with coverage.

  test:coverage:flutter:
    run: dart run melos exec -- "flutter test --coverage"
    packageFilters:
      dirExists: test
      flutter: true
    description: Run Flutter tests with coverage.

  generate:
    run: dart run melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    packageFilters:
      dependsOn: build_runner
    description: Run `build_runner` for packages that depend on it.
